# Generated by Django 3.1.2 on 2020-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='foo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
